<?php
header('Content-Type: application/xml; charset=utf-8');
$domain = $_SERVER['HTTP_HOST'];
echo '<?xml version="1.0" encoding="UTF-8"?>';?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://<?=$domain?>/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>1.0</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/oborudovaniye/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/servis/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/aktsii/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/dostavka/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/tekhnika-na-gazomotornom-toplive/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/v-chelyabinske-dlya-uborki-trotuarov-i-obshchestvennykh-prostranstv-zakupili-sovremennuyu-tekhniku/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/o-zavode/test-drive/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/vakuumnye-podmetalno-uborochnye-mashiny/ko-318f-faun/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/o-zavode/vakansii/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/o-zavode/istoriya-zavoda/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/oborudovaniye/navesnoe-dlya-mini-pogruzchika/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/servis/obuchenie-i-obsluzhivanie/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/kombinirovannye-dorozhnye-mashiny/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/servis/pereoborudovanie/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/vakuumnye-podmetalno-uborochnye-mashiny/ko-318d/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/smi-o-nas/kommunalshchiki-anapy-poluchili-srazu-8-edinits-novoy-spetstekhniki/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/o-zavode/proizvodstvo/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/avtogudronatory/kornet-8000/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/dilery-i-servis/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/avtogudronatory/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/chipsilery/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/smi-o-nas/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/zakupki/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/snegopogruzchiki/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/o-zavode/upravleniye-kachestvom/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/mini-pogruzchiki/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/obrabotka-personalnykh-dannykh/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/snegopogruzchiki/irbis-350/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/zapchasti/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/vakuumnye-podmetalno-uborochnye-mashiny/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/prodazha-v-regionakh/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/kontakty/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/o-zavode/partnery/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/mini-pogruzchiki/termit-1000/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/oborudovaniye/otvaly/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/servis/individualnoe-proektirovanie/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/o-zavode/litsenzii-i-sertifikaty/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/gotovaya-produktsiya/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/oborudovaniye/polivomoechnoe-oborudovanie/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/populyarnyye-voprosy/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/o-zavode/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/oborudovaniye/peskorazbryzgivateli/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/servis/vyezdnoy-servis/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/vakuumnye-podmetalno-uborochnye-mashiny/ukm-2500/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/o-zavode/galereya/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/o-zavode/sotrudniki/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/servis/garantiynoe-obsluzhivanie/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/servis/lizing/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/smi-o-nas/kurgandormash-budet-vypuskat-sovershenno-novuyu-tekhniku-kotoruyu-v-rossii-ne-delaet-nikto/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.9</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/gotovaya-produktsiya/termit-1000/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/gotovaya-produktsiya/kornet-8000/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/gotovaya-produktsiya/ko-318f-faun/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/aktualnye-voprosy-razvitiya-i-rosta-kurgandormash-v-intervyu-avdalova-yu-a-na-vystavke-bauma-ctt-201/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/s-prazdnikom-s-dnem-rossii-2019/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/sankt-peterburg-zakupaet-tekhniku-kurgandormash-na-polmilliarda-rubley/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/dilerskiy-tsentr-kamaz-mersedes-sovmestno-s-ao-kurgandormash-pristupili-k-vydache-avtomobiley-dlya-o/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/na-ulitsakh-ufy-nachali-rabotat-kurganskie-pylesosy-kotorye-sobirayut-opavshuyu-listvu/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/smi-o-nas/kurgandormash-po-itogam-2018-goda-zavod-milliardnik/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/smi-o-nas/kurgandormash-predstavil-svoyu-tekhniku-polnomochnomu-predstavitelyu-prezidenta-rossii-v-urfo-nikola/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/smi-o-nas/v-chelyabinske-dlya-uborki-trotuarov-i-obshchestvennykh-prostranstv-zakupili-sovremennuyu-tekhniku/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/kurganskaya-oblast-vpervye-predstavlena-na-vystavke-dorozhnoy-tekhniki-mirovogo-urovnya-bauma-2019-v/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/kurgandormash-prinyal-uchastie-v-mezhdunarodnoy-vystavke-shelkovyy-put/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/priglashaem-vas-na-vystavku-bauma-ctt-2019/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/priglashaem-vas-na-vystavku-kazavtodor-2018-v-astane-28-29-noyabrya/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/kurgandormash-prinyal-uchastie-v-vystavke-kyrgyzcomex-2019/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/priglashaem-na-vystavku-doroga-2019-v-ekaterinburge/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/den-predprinimatelya-2019-v-kurgane/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/zavershilas-ezhegodnaya-mezhdunarodnaya-vystavka-kazavtodor-kaztraffic-2018/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/kurgandormash-predstavil-svoyu-tekhniku-na-mezhdunarodnom-avtoprobege/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/na-zavode-kurgandormash-proveli-master-klass-dlya-studentov-kgu/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/8-noyabrya-2018-goda-v-moskve-zavod-kurgandormash-prinyal-uchastie-v-kachestve-spikera-na-seminare-r/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/kurgandormash-prinyal-uchastie-v-delovoy-missii-rossiyskikh-kompaniy-v-azerbaydzhan/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/kurgandormash-prinyal-uchastie-v-mezhdunarodnom-forume/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/kruglyy-stol-dorozhnoe-stroitelstvo-dalniy-vostok-2019/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/rukovoditeli-krupnykh-promyshlennykh-predpriyatiy-goroda-prishli-v-gosti-k-studentam-tekhnicheskikh-/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/v-kontse-yanvarya-v-krasnoyarske-zavod-kurgandormash-prinyal-uchastie-v-kachestve-spikera-na-seminar/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/smi-o-nas/zavod-kurgandormash-pervym-v-zaurale-voshel-v-natsproekt-po-povysheniyu-proizvoditelnosti-truda/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/studenty-tyumenskogo-industrialnogo-universiteta-posetili-kurgandormash/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/s-novym-2020-godom/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/smi-o-nas/itogi-goda-2019-v-intervyu-yuriya-avdalova/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/smi-o-nas/gubernator-sankt-peterburga-proveril-kak-tekhnika-kurgandormasha-gotova-k-borbe-so-snegom/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/avtogudronatory/is/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/avtogudronatory/ds-53605/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/avtogudronatory/ds-138/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/tekhnika-na-gazomotornom-toplive/md-532g/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/kombinirovannye-dorozhnye-mashiny/md-43253/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/tekhnika-na-gazomotornom-toplive/ko-318f/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/chipsilery/ds-180/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/kombinirovannye-dorozhnye-mashiny/md-651/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/avtogudronatory/ds-c41r1/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/vakuumnye-podmetalno-uborochnye-mashiny/ko-318t/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/kombinirovannye-dorozhnye-mashiny/md-532/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/avtogudronatory/ds-142/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/vakuumnye-podmetalno-uborochnye-mashiny/ko-318n/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/kombinirovannye-dorozhnye-mashiny/md-43118/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/vakuumnye-podmetalno-uborochnye-mashiny/ko-5340/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/kombinirovannye-dorozhnye-mashiny/md-53605/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/kombinirovannye-dorozhnye-mashiny/md-5340/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/tekhnika-na-gazomotornom-toplive/md-53605g/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/kombinirovannye-dorozhnye-mashiny/md-651a/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/avtogudronatory/ds-5340/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/tekhnika-na-gazomotornom-toplive/md-651g/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/kombinirovannye-dorozhnye-mashiny/md-s41r1/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/oborudovaniye/otvaly/skorostnoy-1100/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/catalog/avtogudronatory/ds-43253/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/oborudovaniye/otvaly/bokovoy/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/oborudovaniye/otvaly/peredniy-gidropovorot/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/oborudovaniye/otvaly/skorostnoy-1500/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/oborudovaniye/otvaly/peredniy-povorotnyy/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/oborudovaniye/otvaly/skorostnoy-1250/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/oborudovaniye/otvaly/sredniy-greydernyy-nozh/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-43253g/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-43253/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-650/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-5349/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-651a/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-s41/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-651g/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-651a-metan/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-53605g/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-53605/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-532g/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-651/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-43118/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/kurgandormash-posetili-partnery-iz-belarusi/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-532/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/configurator/md-43118g/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/kurgandormash-peredal-tekhniku-v-sankt-peterburg/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/v-mordovii-proshel-parad-kommunalnoy-tekhniki/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/pozdravlenie-s-novym-godom/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/kurgandormash-osvaivaet-rynki-gruzii-i-armenii/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/sobytiya/prezentatsiya-tekhniki-v-sankt-peterburge/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/tekhniku-predpriyatiya-kurgandormash-pokazhut-na-vystavke-v-mongolii/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/xxii-mezhdunarodnaya-spetsializirovannaya-vystavka-surgut-neft-i-gaz-2017/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/kurgandormash-uchastvuet-v-vystavke-doroga-2018-v-kazani/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/kurgandormash-predstavit-termita-na-4-oy-mezhdunarodnoy-vystavke-importozameshchenie/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/kurgandormash-primet-uchastie-v-vystavke-bauma-ctt-russia/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/tekhniku-kurgandormasha-otsenil-ministr-promyshlennosti-rossii/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/vystavki/predstaviteli-zavoda-posetili-partnerov-na-vystavke-ifat-v-myunkhene/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/s-mezhdunarodnym-zhenskim-dnem-s-8-marta/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/s-dnem-vesny-i-truda/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/kollektiv-zavoda-kurgandormash-pozdravlyaet-vsekh-s-velikim-prazdnikom-dnyem-pobedy/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/s-dnem-zashchitnika-otechestva-s-23-fevralya/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/na-zavode-kurgandormash-podveli-itogi-konkursa-detskogo-risunka-moya-mama/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/kurgandormash-postavil-novuyu-tekhniku-dlya-uborki-ulits-kurgana/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/sotrudniki-zavoda-kurgandormash-pozdravili-veteranov-velikoy-otechestvennoy-voyny/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/kurgandormash-pokazal-podrastayushchemu-pokoleniyu-svoye-proizvodstvo/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/itogi-vystavki-bauma-ctt-2018-v-intervyu-kommercheskogo-direktora-evgeniya-lovtsova/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/kazakhstan-ispolzuet-shpo-v-tselyakh-predotvrashcheniya-dorog-ot-razrusheniya/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/vnimanie-opasaytes-nedobrosovestnykh-postavshchikov-i-kontrafaktnoy-produktsii/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/kurgandormash-postavit-svoyu-tekhniku-v-tatarstan/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/pozdravlenie-s-dnem-rabotnikov-bytovogo-obsluzhivaniya-naseleniya-i-zhilishchno-kommunalnogo-khozyay/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/ao-kurgandormash-prinyal-uchastie-v-prazdnovanii-dnya-goroda-kurgana-25-avgusta/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/v-krymu-proshli-ispytaniya-ko-318f/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/sravnenie-oborudovaniya-po-raspredeleniyu-pgm/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/dorozhnye-mashiny-md-651-s-kuzovom-iz-nerzhaveyushchey-stali-pristupyat-k-ochistke-dorog-v-orle/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/pozdravlyaem-s-novym-2019-godom-/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/novaya-vakuumnaya-podmetalno-uborochnaya-mashina-ko-318d-peredana-vladivostoku/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/pozdravlyaem-s-dnem-mashinostroitelya-2018/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/tekhnika-kurgandormash-rabotaet-v-belorussii/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/v-novocherkassk-pribyla-partiya-novoy-kommunalnoy-tekhniki/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/dorozhnye-mashiny-proizvodstva-kurgandormash-budut-rabotat-v-moldavii/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/18-sentyabrya-v-zlatoustovskom-gorodskom-okruge-prezentovali-sovremennuyu-uborochnuyu-tekhniku-dlya-/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/razrabotka-novoy-spetstekhniki-sovmestno-s-yuurgu/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/kurgandormash-predstavil-ukm-2500-na-parade-kommunalnoy-tekhniki-v-mordovii/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/sravnenie-krupnogabaritnykh-raspredeliteley-pgm-schmidt-stratos-giletta-epoke/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
    <url>
        <loc>https://<?=$domain?>/novosti/novosti/novye-razrabotki-sovmestno-s-tsentrom-kompyuternogo-inzhiniringa-yuurgu/</loc>
        <lastmod>2020-07-21</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.7</priority>
    </url>
</urlset>
